### ISSUE TITLE
Обновление Dayz Linux Server

### ISSUE THREAD

**Issue by aGaming** [denisio/Dayz-Linux-Server#2]
Добрый день, коротко опишу проблему . Пользуюсь античитом "Infistar", после последнего обновления античита, он перестал работать с сервером. При заходе в игру он пишет обновить бета патч, ниже бета патча 103718 отказывается работать. Готов компенсировать ваш труд (обновление бетапатча), если у вас нет времени, то хотя бы ткните носом какие файлы нужно обновить. Файлы Армы которые лежат вместе с сервером обновлены до 108074.
Заранее спасибо за ответ.

**Comment by denisio** [comment]
Привет,

Какая версия infistar ?

**Comment by aGaming** [comment]
Извините, нахожусь на работе. AH0324, официальное обновление было 25 февраля, этого года. На сайте смотрю еще обновление появилось у них от 7 марта. У меня предыдущее. 
Я так понимаю, проблемы в самом античите?

**Comment by aGaming** [comment]
Вопрос решен, после обновления античита. Спасибо за содействие.
